# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Inhalte
    url: '#inhalte'
    weight: 20
  - name: Forschungsschwerpunkte
    url: '/post/forschungsschwerpunkte_ger/'
    weight: 30
  - name: Curriculum Vitae
    url: '/post/curriculum-vitae_ger/'
    weight: 40
  - name: Publikationen
    url: '/post/publikationsliste_ger/'
    weight: 50
  - name: Publikationsliste
    parent: Publikationen
    url: '/post/publikationsliste_ger/'
    weight: 51
  - name: Publikationsliste nach Forschungsschwerpunkten
    parent: Publikationen
    url: '/post/publikationsliste_forschungsschwerpunkte_ger/'
    weight: 52
  - name: Fremdsprachige Publikationen
    parent: Publikationen
    url: '/post/publikationsliste_foreign_ger/'
    weight: 53

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
