# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Inhalte
    url: '#inhalte'
    weight: 20
  - name: Forschungsschwerpunkte
    url: '/post/forschungsschwerpunkte/'
    weight: 30
  - name: Curriculum Vitae
    url: '/post/curriculum-vitae_ger/'
    weight: 40
  - name: Publikationsliste
    url: '/post/publikationsliste/'
    weight: 50
  - name: Kontakt
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
